site_name: Aim Scenario Maker
site_url: https://asm.bellalabs.dev/
repo_url: https://github.com/bella-labs/OW2-Aim-Scenario-Maker

docs_dir: 'docs/'
site_dir: 'generated/'

theme:
  name: material
  custom_dir: 'overrides/'
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico    
  features:
    - toc.integrate
  palette:
    scheme: slate

plugins:
  - search                  
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ko
          name: 한국어
          build: true
          nav_translations:
              Home: homeinko
              #Getting Started: 
              Menu Reference: menureferenceinko 
        - locale: zh
          name: 中文
          build: true
          nav_translations:
              Home: homeinzh
              #Getting Started: 
              Menu Reference: homeinzh

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bella-labs
      name: OW2-Aim-Scenario-Maker on Github
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/a_bella_ciao

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
- Home: index.md
- Getting Started: 
  - getting_started/get_started_index.md
  - Export: getting_started/export_instructions.md
  - Import: getting_started/import_instructions.md
- Menu Reference:
  - Main Menu: menu_ref/menu_ref_main.md
  - Scenario: menu_ref/menu_ref_scenario.md
  - Bot: menu_ref/menu_ref_bot.md
  - Profile: menu_ref/menu_ref_movement.md


extra_css:
  - stylesheets/custom_colors.css

#use_directory_urls: false